version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
  #  volumes:
  #     - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"

  # logstash:
  #   build: .
  #   volumes:
  #     - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     #- ./logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./news.db:/tmp/input.db
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"

#    depends_on:
#      - elasticsearch

  dejavu:
      image: appbaseio/dejavu:3.0.0-alpha
      ports:
        - "1358:1358"
