version: '2'
services:
  logstash:
    build: .
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./news.db:/tmp/input.db
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    command: "logstash -f /usr/share/logstash/pipeline/logstash.conf"
